### ISSUE TITLE
There maybe a problem in the code?

### ISSUE THREAD

**Issue by xuChenSJTU** [Songweiping/GRU4Rec_TensorFlow#4]
Hello, @Songweiping
I use the processed data processed from:  https://github.com/hidasib/GRU4Rec
When I run this main.py,  but I get this error:
![image](https://user-images.githubusercontent.com/24096174/34301745-cc77fac8-e768-11e7-9a97-56bbc3c56b5c.png)
![image](https://user-images.githubusercontent.com/24096174/34301936-a519dba8-e769-11e7-8497-53a1586556cf.png)

I am wondering what cause this? Could you give me some advice?

**Comment by Songweiping** [comment]
Hi @xuChenSJTU,

It seems no one had this problem. I can not tell what caused this error due to the limited information. Would you please provide some details?
1) Which dataset are you using and the size of dataset.
2) Is data format valid?
3) When does this error occur? In the first mini-batch or last mini-batch of training data? 
Check these issues first and hope they help.

Weiping

**Comment by xuChenSJTU** [comment]
Hi, @Songweiping 
Thank you for your advice. I have found that this problem is due to my small test dataset. When I utilize a larger dataset, it  works.
Thanks very much.

Chen Xu
